// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Driven.SqlLite.Data;

#nullable disable

namespace Driven.SqlLite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Core.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasName("IX_Cliente_Ativo");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasName("IX_Cliente_Cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("IX_Cliente_Email");

                    b.HasIndex("Nome")
                        .HasName("IX_Cliente_Nome");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core.Domain.Entities.InformacoesFinanceirasCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnaliseRiscoCredito")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AptoParaCartaoCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtrasosDiversos12Meses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartoesEmitidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditosEmAberto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProximaAnaliseRecomendada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAnalise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteCreditoAtivo")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteCreditoSugerido")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recomendacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Renda")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RendaComprovada")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RankingCredito")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreCredito")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDebitos")
                        .HasPrecision(15, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasName("IX_InformacoesFinanceiras_ClienteId");

                    b.HasIndex("RankingCredito")
                        .HasName("IX_InformacoesFinanceiras_RankingCredito");

                    b.HasIndex("ScoreCredito")
                        .HasName("IX_InformacoesFinanceiras_ScoreCredito");

                    b.ToTable("InformacoesFinanceirasClientes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataBloqueio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAlteracaoSenha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoBloqueio")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaSalt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasLoginFalhadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenConfirmacaoEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasName("IX_Usuario_Ativo");

                    b.HasIndex("ClienteId")
                        .HasName("IX_Usuario_ClienteId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("IX_Usuario_Email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasName("IX_Usuario_Login");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Domain.Entities.InformacoesFinanceirasCliente", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
